### PR TITLE
feat: add code-cov on commit

### PR DESCRIPTION
**Pull request by sravan-s**

### CODE REVIEW

**Review by AhyoungRyu — APPROVED** [review]
🚀

**Review by AhyoungRyu — APPROVED** [review]

**Review by AhyoungRyu — APPROVED** [review]

**Comment by HoonBaek** [comment]
why don't we merge this? @sravan-s

**Comment by sravan-s** [comment]
Will do next week, maybe use circle CI :)

**Comment by sravan-s** [comment]
cc @chrisallo

**Pull request closed without merging**
