### PR TITLE
Prepare release 3.4.7

### PR DESCRIPTION
**Pull request by AhyoungRyu**
## [v3.4.7] (May 4 2023)

Features: 
* Set Chat SDK v4.3.0 as the minimum required version.
* Add a new UI component, Toggle:
  * `ToggleContainer`: A context provider component that manages only the toggle status.
  * `ToggleUI`: A UI component that does not include the status managing logic.
  * `Toggle`: A combination of ToggleContainer and ToggleUI components.
  * `useToggleContext`: A custom useContext hook that provides context from ToggleContainer.
  ```javascript
  import { Toggle, ToggleContainer, ToggleUI,  useToggleContext } from '@sendbird/ui/Toggle';
  ```
  
Fixes:
* Apply `isMuted` to the participant list. Operators can now unmute the muted participants from the participant list.
* Update the max mention count notice message.
* Modify the URL Regex to filter various types of formats.
* Give a left margin to the link text inside the message.
* Move the message list scroll after the OG image is loaded.

Chores: 
* Rewrite the connection logic in sdk/thunks to hooks/useConnect
  ```
  const reconnect = useConnect({
    appId,
    userId,
    accessToken,
  }, {
    logger,
    nickname,
    profileUrl,
    configureSession,
    customApiHost,
    customWebSocketHost,
    sdk: sdkStore?.sdk,
    sdkDispatcher,
    userDispatcher,
  });
  ```
* Rename `smart-components/` to `modules/`.
* Modify Logger method:
  * The first parameter (log message) of the method is now required.
  * Any other values can be passed to the second parameter of the method in a key-value format.

[SDKRLSD-798](https://sendbird.atlassian.net/browse/SDKRLSD-798)

[SDKRLSD-798]: https://sendbird.atlassian.net/browse/SDKRLSD-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sravan-s — APPROVED** [review]
Looking good, I am testing ~

**Review by sravan-s — CHANGES_REQUESTED** [review]
Ops wait for me to test :D

**Review by HoonBaek — COMMENTED** [review]
Could you add these too?

```
Fixes:
* Specify the getSdk returns SendbirdGroupChat or SendbirdOpenChat
* Remove the channel list dependency from the `useEffect` of useActiveChannelUrl to fix the current channel flickers on the channel list
```

**Comment by sravan-s** [comment]
How about 

```
* Current channel flicker on the ChannelList while creating a new group channel
```
cc @HoonBaek

**Comment by HoonBaek** [comment]
@sravan-s also good

**Comment by AhyoungRyu** [comment]
@sravan-s @HoonBaek Just added more bullet items as you guys requested 
https://github.com/sendbird/sendbird-uikit-react/pull/519/commits/cba6149b35660e92ecb167269098c3f4d2c4c63b

**Review by sravan-s — APPROVED** [review]
LGTM

**Pull request merged**
