### PR TITLE
chore: enable more lint rules

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### Description Of Changes
Resolves https://sendbird.atlassian.net/browse/UIKIT-3837

Enabled some eslint rules off-ed by #490 previously. 
 - [semi](https://eslint.org/docs/latest/rules/semi#rule-details) - this made the total # of file changes a bit huge 😅
 - [no-useless-return](https://eslint.org/docs/latest/rules/no-useless-return)
 - [no-floating-decimal](https://eslint.org/docs/latest/rules/no-floating-decimal#rule-details)

### CODE REVIEW

**Comment by sravan-s** [comment]
If its not too inconvenient,  can we split this into 3 PRs? (If too much, dont need to)

**Comment by sravan-s** [comment]
Changes look okay, but for specificity (especially because `semi` is a big hit ~)

**Review by sravan-s — APPROVED** [review]
Quick scan, looks good ~

**Comment by sravan-s** [comment]
Thankyou so much

**Comment by AhyoungRyu** [comment]
Just split into 3 #522 #523 #524 as you said. I'm closing this one :)

**Pull request closed without merging**
