### PR TITLE
release: [v3.6.1] (June 30 2023)

### PR DESCRIPTION
**Pull request by sravan-s**
### Feat:
* Enable channel creation when no user present to select
* Mobile: Keep keyboard open after sending the message

### Fixes:
* Update @sendbird/uikit-tools to 0.0.1-alpha.39
    alpha.39 has CJS support, otherwise, UIKit wont work
    on next-js page router

### Chore:
* Update all examples to V4 + StackBlitz
  * Update all sample code to V4
  * Convert CodeSandbox to StackBlitz
  * Render all examples with Vite
  * Thanks @tylerhammer

### CODE REVIEW

**Comment by sendbird-sdk-deployment** [comment]
[Creating Ticket] 🔖 Done https://sendbird.atlassian.net/browse/SDKRLSD-891

**Comment by sravan-s** [comment]
https://www.youtube.com/watch?v=KSQ-xv8ZLQg

**Review by HoonBaek — APPROVED** [review]

**Review by AhyoungRyu — APPROVED** [review]
🚀🚀🚀

**Comment by sravan-s** [comment]
Screen Shot 2023-06-30 at 2 51 22 PM

**Pull request merged**
