### PR TITLE
refactor: Add tests for ChannelSettings migration

### PR DESCRIPTION
**Pull request by HoonBaek**
fix: Prevent destroy error by adding `AbortController` in `useSetChannel`
- Added `AbortController` to cancel async operations when the component unmounts.
- Ensured that state updates are skipped if the operation is aborted.
- Prevented potential memory leaks and the `'destroy is not a function'` error.
- Updated `useEffect` cleanup to properly handle pending async calls.

feat: Add tests for ChannelSettings migration

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
Leaving the test coverage for the ChannelSettings module before and after this change
- Before 
Screenshot 2024-10-21 at 2 44 47 PM

- After 
Screenshot 2024-10-21 at 2 43 17 PM

**Comment by HoonBaek** [comment]
The hook which calls `setLoading` and `setInvalid` is the `useSetChannel` hook.
And I made a separate test for it, so, should I remove the two tests?
@AhyoungRyu

**Comment by AhyoungRyu** [comment]
@HoonBaek Yeah I think we can remove them if that's the case.

**Comment by HoonBaek** [comment]
image
Test coverage hasn't been changed after removing the two tests, let me remove them!

**Review by AhyoungRyu — APPROVED** [review]
👍

**Pull request merged**
