### PR TITLE
Pass missing properties to renderChatItem

### PR DESCRIPTION
**Pull request by satya-imaginea**
## Description Of Changes

We have date seperator in ui kit, but if anyone want to use their custom components like chatItem, chat message, they have to struggle to identify the date seperator in between messages, so adding it as it is readyly available before calling the renderChatItem

Please refer - https://community.sendbird.com/t/please-add-additioinal-props-to-renderchatitem/2731

## Types Of Changes

- [y] Bugfix
- [y] New feature
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance (ex) Prettier)
- [ ] Build configuration
- [ ] Improvement (refactor code)

### CODE REVIEW

**Comment by satya-imaginea** [comment]
@sravan-s @HoonBaek

**Comment by tylerhammer** [comment]
Hi @satya-imaginea, FYI we do not accept external pull requests.

**Comment by satya-imaginea** [comment]
> Hi @satya-imaginea, FYI we do not accept external pull requests.

Thanks for the quick reply @tylerhammer, I would use a forked repository.

**Comment by HoonBaek** [comment]
Thanks @satya-imaginea 
It will be applied in https://github.com/sendbird/sendbird-uikit-react/pull/13

**Pull request closed without merging**
