### PR TITLE
fix: cannot delete property renderMessage of Object

### PR DESCRIPTION
**Pull request by HoonBaek**
### Fix
* Figure out error: `Cannot delete property `renderMessage` of #<Object> when using the `renderMessage` props

### Issue
* This error appears from the customer side while I try to use the props `renderMessage` of Channel
image

### CODE REVIEW

**Review by bang9 — COMMENTED** [review]
```ts
const renderedMessage = useMemo(() => renderMessage?.(omitObjectProperties(props, ['renderMessage'])), [message, renderMessage]);
```

When viewed from a different perspective, are there any benefits to removing renderMessage from props? 🤔

**Comment by HoonBaek** [comment]
@bang9 It looks a little bit weird that the parameter of the `renderMessage` has a `renderMessage`

**Comment by bang9** [comment]
> @bang9 It looks a little bit weird that the parameter of the `renderMessage` has a `renderMessage`

Yes, so we're actually handling it with Omit in terms of types.
`type RenderMessageParamsType = Omit<MessageProps, 'renderMessage'>;`

However, in the actual code, we're not just passing `MessageProps` but passing all the values of `MessageViewProps`, so I was wondering if removing only renderMessage would make a significant difference.

**Review by bang9 — APPROVED** [review]

**Review by liamcho — APPROVED** [review]
LGTM

**Pull request merged**
