### PR TITLE
release: 3.6.10

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### Fixes:
* (in Safari) Display the placeholder of the MessageInput when the input text is cleared
* Remove duplicated CSS line
* (in iOS) fix focusing on the chat screen starts from the top in Mobile device

### CODE REVIEW

**Comment by sendbird-sdk-deployment** [comment]
[Creating Ticket] 🔖 Done https://sendbird.atlassian.net/browse/SDKRLSD-1013

**Comment by AhyoungRyu** [comment]
Just to make sure where I made the build 
Screenshot 2023-10-11 at 5 42 10 PM

**Review by liamcho — APPROVED** [review]
LG2M

**Pull request merged**
