### PR TITLE
Fix Channel list fetch more issue

### PR DESCRIPTION
**Pull request by mango906**
## External Contributions

This project is not yet set up to accept pull requests from external contributors.

If you have a pull request that you believe should be accepted, please contact
the Developer Relations team <developer-advocates@sendbird.com> with details
and we'll evaluate if we can setup a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the contribution.

## Description Of Changes

Hello ! We are developing products using sendbird-uikit. 
I opened this PR because there was a problem with the ChannelList component while using uikit.
ChannelList was not fetching more at some resolutions.
If the sum of clientHeight and scrollTop is exactly the same as scrollHeight, fetching more channels code will be excuted.

```typescript
const fetchMore = target.clientHeight + target.scrollTop === target.scrollHeight;
```

But, At some resolutions, it operates as follows.

image

The channel is not fetching more because it is not exactly same. 
So, I think it would be good to change the logic of fetching more by referring to the code of the MessageList component as follows.

https://github.com/sendbird/sendbird-uikit-react/blob/1bcbef99109f47bf0649f123cb818275b500816b/src/smart-components/Channel/components/MessageList/index.tsx#L72-L82

The `isAboutSame` function is a channel dependent util, so I move it to public util folder.  (This change is okay not to be reflected.)

I would really appreciate it if you could review this PR. 

Thanks :)

## Types Of Changes

What types of changes does your code introduce to this project?
Put an `x` in the boxes that apply_

- [x] Bugfix
- [ ] New feature
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance (ex) Prettier)
- [ ] Build configuration
- [x] Improvement (refactor code)

### CODE REVIEW

**Comment by hellfreya** [comment]
@mango906 안녕하세요. 
PR 너무 감사드립니다. 미리미리 정리를 했었어야 하는데, 버그 수정이 늦어진 점 대단히 죄송합니다. 
내부적으로 관리하는 레포지토리가 따로 있고, 공식적인 정책은 public repository에 PR에 대한 처리는 하지 않고 있습니다. 
이에 따라 수정하신 내용 참고하여 빠른 시간내에 반영을 할 수 있도록 하겠습니다.
다음에도 잘 부탁드립니다! 감사합니다.

**Comment by mango906** [comment]
> 

@hellfreya 안녕하세요. 혹시 관련된 내용으로 업데이트 된 내용이 있을까요 ??

**Comment by sravan-s** [comment]
@mango906 We have a release on Nov 7-9, Will include this fix in that

**Comment by mango906** [comment]
> fix: Expect not to be accurate height of channel list #349

Thank you for your reply. I'll be waiting for the release. Thanks :)

**Pull request closed without merging**
