### PR TITLE
use disableAutoSelect from ChannelListProvider props in initial state

### PR DESCRIPTION
**Pull request by neilfulwiler**
## External Contributions

This project is not yet set up to accept pull requests from external contributors.

If you have a pull request that you believe should be accepted, please contact
the Developer Relations team <developer-advocates@sendbird.com> with details
and we'll evaluate if we can setup a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the contribution.

## For Internal Contributors

[<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)

## Description Of Changes

Add a brief description of the changes that you have involved in this PR

## Types Of Changes

What types of changes does your code introduce to this project?
Put an `x` in the boxes that apply_

- [ ] Bugfix
- [ ] New feature
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance (ex) Prettier)
- [ ] Build configuration
- [ ] Improvement (refactor code)

### CODE REVIEW

**Comment by sravan-s** [comment]
Hi @neilfulwiler can you share the context of the fix?

**Comment by neilfulwiler** [comment]
Hey @sravan-s! Yes of course, after submitting I saw the big block about external contributions, but realize it would help to provide context anyway.

Basically if you specify disableAutoSelect in the ChannelListProvider that doesn't actually propagate down into the channelListReducer (which seems to have its own disableAutoSelect state although this state is never mutated), which means that disableAutoSelect effectively doesn't work right now for the ChannelListProvider. This fix just pushes through that flag into the initialState used with the reducer so it should fix what we're seeing

**Comment by sravan-s** [comment]
@neilfulwiler Thanks for the contribution..

About the open source contribution guidelines, bug fixes like these are fine. Its usually the larger features contributions that we might not accept

**Comment by HoonBaek** [comment]
Thank you @neifulwiler I modified this issue and it's a hundred percent thanks to you 🙏
(I fixed it to fit our convention) https://github.com/sendbird/sendbird-uikit-react/pull/152

**Pull request closed without merging**
