### PR TITLE
release: v3.13.4

### PR DESCRIPTION
**Pull request by HoonBaek**
### Features
* Add support for the `Emoji Reactions` feature in super group channels.
  * Note: The `Tooltip` that displays who has reacted will only appear in normal group channels, not in super group channels.
* Export the `MessageFeedbackFailedModal` component for consistency with other message feedback-related components.

### CODE REVIEW

**Comment by sendbird-sdk-deployment** [comment]
[Creating Ticket] 🔖 Done https://sendbird.atlassian.net/browse/SDKRLSD-1202

**Comment by AhyoungRyu** [comment]
Rebased from main after #1031 & #1029 merged

**Review by liamcho — APPROVED** [review]
LGTM

**Pull request merged**
