### PR TITLE
Fix: Compilation issue Element not defined

### PR DESCRIPTION
**Pull request by aburgel**
## Description Of Changes

This fixes compilation issues, something about `Element` not being defined.

## Types Of Changes

- [x] Bugfix
- [ ] New feature
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance (ex) Prettier)
- [ ] Build configuration
- [ ] Improvement (refactor code)

### CODE REVIEW

**Review by sravan-s — COMMENTED** [review]
Hey, thanks for the support, we need to talk to the team before applying this(to check company policy) ~~

**Comment by aburgel** [comment]
if you can't apply it, it should be easy enough to fix it in some other way 😄

**Comment by sravan-s** [comment]
Hahah, of course we will take it, just making sure how to give you credit

**Comment by aburgel** [comment]
How about `Inspired by @aburgel` in the commit 😉

**Review by sravan-s — APPROVED** [review]

**Pull request merged**
