### PR TITLE
feat: make integrated toggle config options resettable

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### Description Of Changes
I was preparing a sample app environment for Feature Configuration war room but realized that there's no way to set `undefined` for the toggle items but only possible to choose `true` or `false` in this integration app.

So I added a checkbox next to the each toggle button like this (yeah couldn't come up with a better UI :smile: Any suggestion is welcome!)
recording
 
Like the above in the gif, we can make each config value to `undefined` from boolean value by uncheck the checkbox.

### CODE REVIEW

**Review by sravan-s — APPROVED** [review]
cc @HoonBaek

**Comment by sravan-s** [comment]
Screen Shot 2023-06-09 at 6 17 53 PM

**Comment by bang9** [comment]
We have an additional unwanted undefined -> string here

https://github.com/sendbird/sendbird-uikit-react/pull/630/files#diff-abe6979fd8fc2c7335fbb3046b881582063c281e8e8d101421d6b42323da977cR121

**Comment by AhyoungRyu** [comment]
@bang9 Thanks for checking out. Just applied the both comments 

 -  [Prevent initialized replyType goes inside unintentionally](https://github.com/sendbird/sendbird-uikit-react/pull/630/commits/a96a697426b1e8696112e8ccb112064bcb19b9d4)
 - [Added an option to replyType ](https://github.com/sendbird/sendbird-uikit-react/pull/630/commits/1380102ca59abd983eb5fd980dc45c88670ecf37)
 Screenshot 2023-06-12 at 10 40 58 AM

**Pull request merged**
